site_name: mkdocs-feather
  plugins:
    feather:
      server_url: https://feather-demo.herokuapp.com
theme:
  name: material
repo_url: https://github.com/pipalacademy/mkdocs-feather
edit_uri: edit/main/docs/
nav:
  - Home: index.md
